version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_URI=mongodb://root:root@mongo/test_db
    ports:
    - 8080:8080 # host:container
    depends_on:
      - mongo
    networks:
      - integration_test


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - integration_test

  mongo:
    image: 'mongo:4.2.8'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-script/:/docker-entrypoint-initdb.d/:ro
    ports:
      - '27017:27017'
    networks:
      - integration_test

networks:
  integration_test:
